### ISSUE TITLE
SSL + new core 2.4.1 ESP8266

### ISSUE THREAD

**Issue by Fenogik** [marvinroger/async-mqtt-client#102]
Today there was a problem.
 I have Arduino IDE 1.8.5. Core 2.4.0.rc2. Library AsyncMqttClient. I use ASYNC_TCP_SSL_INABLE = 1.
After the upgrade core 2.4.1, the SSL stopped working. 
Moscoitto Broker Server: OpenSSL Error: error: 140940E5: SSL routines: ssl3_read_bytes: ssl handshake failure

**Comment by timpur** [comment]
With try look into this week

**Comment by bertmelis** [comment]
should be solved by now.

**Comment by kleini** [comment]
I tested with core 2.6.3 and develop branch and it works very well.
