### ISSUE TITLE
setWill() not work.

### ISSUE THREAD

**Issue by lucasmaziero** [marvinroger/async-mqtt-client#108]
Hello, the setWill () function is not working, the server does not apply the "Last Will and Testament" changes after the device stay offline. I'm using the iot.eclipse.org broker.

**Comment by mvsistema** [comment]
Você está setando as variáveis do tópico e payload no escopo global?

**Comment by lucasmaziero** [comment]
Yes, all variables global.

**Comment by mvsistema** [comment]
My project is working well. Use pastebin.com to show your code

**Comment by lucasmaziero** [comment]
All working well now. thank you
