### ISSUE TITLE
Can't find this library in the platformio library

### ISSUE THREAD

**Issue by FWeinb** [marvinroger/async-mqtt-client#11]
I can't find this library in the platformio library manager? Can you publish it?

**Comment by marvinroger** [comment]
I am pretty limited in bandwidth right now, and I don't have pio either. Can you register it for me? 

http://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#cmd-lib-register

Thanks. :)

**Comment by FWeinb** [comment]
Sure no problem. 

Just did:
```
platformio lib register https://raw.githubusercontent.com/marvinroger/async-mqtt-client/master/library.json
The library has been successfully registered and is waiting for moderation
```

Thanks!

**Comment by marvinroger** [comment]
Thanks! Will update the README link when the lib is approved.

**Comment by marvinroger** [comment]
Done!

**Comment by FWeinb** [comment]
That was quick! Thanks.
