### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by tarbear123** [marvinroger/async-mqtt-client#112]
do I put 
#define WIFI_SSID "My_Wi-Fi"
#define WIFI_PASSWORD "my-awesome-password" and

 void connectToWifi() {
  Serial.println("Connecting to Wi-Fi...");
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

if I want to just connect my esp8266 to wifi and nothing else
I am building a led matrix and want to use the esp8266 to change gif's and stuff on the matrix

**Comment by timpur** [comment]
if you dont need mqtt (this lib) then please see https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/readme.html
