### ISSUE TITLE
BLOCKING?

### ISSUE THREAD

**Issue by sirpete83** [marvinroger/async-mqtt-client#115]
Hallo,
it seems to be blocking the application, when the broker is unreachable. 
can someboby confirm this behavior?
is there a solution for that?
it reconnects if the broker is reachable and countinues working fine.

due to last ESP32 idf update, i'm using the "idf-update" branch of me-no-dev/AsyncTCP

**Comment by bertmelis** [comment]
what is blocking? Connecting? Publishing?

**Comment by bertmelis** [comment]
Cannot reproduce (anymore).
