### ISSUE TITLE
Question , simultaneous station and acces point 

### ISSUE THREAD

**Issue by gnkarn** [marvinroger/async-mqtt-client#122]
Thank you for your sharing your work.

I’m using two esp8266 , #1 is a master with fixed ip, and connects to mosquito mqtt server to receive commands and send state using async mqtt. 

At the same time it creates a soft AP , and connects to esp #2 acting as a slave and connected both using WiFi UDP . 

The connection seams to be unreliable with frequent disconnects , so my question is , based on the complete example for mqtt, what is the proper sequence to get the master esp in sta + softAP mode , mainly on the WiFi setup .

Any help appreciated.

**Comment by jeroenst** [comment]
I also experience bad connection when I have station and softap mode enabled at the same time, but mostly when the station was trying to connect. I disabled wifi.autoreconnect and also prevented wifi.begin to be called when the softap is up. I don't know if this is exactly the same issue as you experience but it sounds familiar. When I used the pubsubclient (synchronous with blocking parts) I didn't experience this issue.

**Comment by gnkarn** [comment]
Ok, I couldn’t found any single example using pubsub or async that makes used of double simultaneous connection . I tried both ways with not good results , on the pubsub I was also using wifimanager probably that is also a source for problems . Thanks

**Comment by gnkarn** [comment]
ok, deleted wifi manager and the  wifi disconnection problem persists.
this is the kind of cycle i see from the logs
so , the code in its parts is working , receiving messages from mqtt , sending udp packets , but all this interruptions makes it unusable.

connected with ssid, channel 8
ip:192.168.0.xx,mask:255.255.255.0,gw:192.168.0.x
ip:192.168.0.x,mask:255.255.255.0,gw:192.168.0.x
Connected to Wi-Fi.
Connecting to MQTT...
Connected to MQTT.

Session present: 0
Subscribing at QoS 1, packetId: 1
Publishing at QoS 1
Subscribe acknowledged.
  packetId: 1
  qos: 1
Publish acknowledged.
  packetId: 2
Disconnected from MQTT.
station: xxxxxx    leave, AID = 1
rm 1
add 1
aid 1
station: xxxxxx   join, AID = 1
Connecting to MQTT...
wifi mode: 3
bcn_timout,ap_probe_send_start
ap_probe_send over, rest wifi status to disassoc
state: 5 -> 0 (1)
rm 0
Disconnected from Wi-Fi.
wifi mode: 3
Connecting to Wi-Fi...
wifimode: 3
scandone
no WIFIgus found, reconnect after 1s
Disconnected from Wi-Fi.
reconnect
1 result found for 'Disconnected from MQTT.'Finding with Options: Case Insensitive

Disconnected from MQTT.

1 found
Find
Find All

Replace in current buffer
Replace
Replace All

**Comment by bertmelis** [comment]
closing, problem most probably outside of the scope of this library.
