### ISSUE TITLE
Bluetooth/Wifi coexistence causes MQTT disconnect and crash

### ISSUE THREAD

**Issue by jptrsn** [marvinroger/async-mqtt-client#123]
When performing a bluetooth low energy scan, MQTT disconnects and results in a Core 1 panic (similar to #99 ). This is only an intermittent issue, so it's difficult to understand how to remedy. It appears to reduce in frequency when the scan duration is shorter. Changing parameters of scan interval and window do not appear to impact the issue.

I'm encountering this bug in my project that scans for BLE devices and reports them via MQTT. You can see the source at [this link](https://github.com/jptrsn/ESP32-mqtt-room/issues/5).

**Comment by bertmelis** [comment]
Disconnecting is reworked completely in `develop` which should solve this issue. Closing.
