### ISSUE TITLE
fully  featured esp32 compilation error

### ISSUE THREAD

**Issue by sheetalsingala** [marvinroger/async-mqtt-client#127]
I'm using the fully-featured-ESP32 example on my ESP 32 wroom.
I get this error on compilation : 
**ESPAsyncTCP.h: No such file or directory**

**Comment by eos1d3** [comment]
@justoke I just tested this with PlatformIO. And I do not have any compilation error. What I did is to copy the FullyFeatured-ESP32.ino file only. And set the library to AsyncMqttClient@0.8.2.

The dependency I see from compilation:

```
Dependency Graph
|-- <AsyncMqttClient> 0.8.2
|   |-- <AsyncTCP> 1.0.3
|-- <WiFi> 1.0
```

**Comment by justoke** [comment]
@eos1d3 Thank you for the tip - I just moved over to Platform IO recently, so this actually makes sense to me now

**Comment by justoke** [comment]
> @eos1d3 Thank you for the tip - I just moved over to Platform IO recently, so this actually makes sense to me now

Glad it helped. Platform IO is really good and I use it almost exclusively for development. It is easier maybe to manage libraries as you can just add links to git repos where you need a specific commit or branch in such situations.
