### ISSUE TITLE
Losing packets only in ESP32 after wifi disconnect and reconnect

### ISSUE THREAD

**Issue by thiagolc3** [marvinroger/async-mqtt-client#135]
Hello.

I tested the example "FullyFeatured-ESP8266.ino" and after the wifi disconnect, the packets published offline are resent after the wifi reconnect.

In the "FullyFeatured-ESP32.ino" packages published when wifi is not available are not resend after wifi reconnect and are lost. How do I solve it?

Thank for attention.

**Comment by bertmelis** [comment]
solved in `develop`
