### ISSUE TITLE
ESP8266 mqtt disconnecting if the frequency of incoming messages is too high

### ISSUE THREAD

**Issue by jassi00713** [marvinroger/async-mqtt-client#141]
I have stable SSL connection to my MQTT Broker using this library.
The ESP is subscribed to a topic and does something whenever there is a publish on that particular topic.

I periodically publish data on that topic and ESP being subscribed to it recieves it and handles it.
Everything is fine till i increase the frequency of publishing to around 200ms or 150 ms.
Then either there is a Watch Dog Reset or the MQTT disconnects.

**Comment by tve** [comment]
I think you want #139...

**Comment by marvinroger** [comment]
Can you test with the latest git rev?
