### ISSUE TITLE
How to connect asyncmqttclient to tinygsm? Or gsm? 

### ISSUE THREAD

**Issue by imranaalam** [marvinroger/async-mqtt-client#142]
where to give tinygsm object in asyncmqttclient?

**Comment by bertmelis** [comment]
you cannot. async-mqtt-client uses asynctcp which uses lwip.

**Comment by poultryAppIndia** [comment]
@bertmelis Do we have any suggestions for this? When the GSM signal is low, it takes a lot of time to connect via PubSubClient. An asynchronous MQTT solution that supports GSM would be great.
