### ISSUE TITLE
mqtt ondisconnect callback not working

### ISSUE THREAD

**Issue by jassi00713** [marvinroger/async-mqtt-client#144]
I have a working script based on AsyncMqttClient running on ESP12F.

I had developed the script on platformio

But after a recent update of the mqtt library, the mqtt ondisconnect callback stoped working.

When i backtrack to 0.8.2 version, everything is fine.
As i update to the latest version available here, the ondisconnect callback stops working.

onConnect
onSubscribe
 mqttClient.connect() ... etc ... everything is working.

But on sudden loss of internet at my router, the mqttclient doesnt call the ondisconnect callback.

It remains like this for infinity amount of time, there is no Timeout called, no ondisconnect callback, nothing.

Kindly look into this.
This is weird because i ran a loop to check in realtime wheather the mqttconnection is present.
In case of internet loss, the mqttclient.connected()  -> returns False as expected but the callback doesn't occur.

It was working in 0.8.2

**Comment by bertmelis** [comment]
does `mqttclient.connected()` return `false` immideately after losing connection or does it take some time (timeout)?

**Comment by jassi00713** [comment]
it takes some time ... doesnt happen immediatelt

**Comment by voidEvgeny** [comment]
Force disconnect cable from the broker or internet cable if your broker in internet and you see how this not work.

**Comment by jeroenst** [comment]
https://github.com/marvinroger/async-mqtt-client/issues/160

**Comment by bertmelis** [comment]
Disconnecting is reworked completely in develop which should solve this issue. Closing.
