### ISSUE TITLE
ssl support?

### ISSUE THREAD

**Issue by kenpeter** [marvinroger/async-mqtt-client#15]
Is it coming any time soon?

**Comment by marvinroger** [comment]
I hope so! It has to be implemented in https://github.com/me-no-dev/ESPAsyncTCP, but I have no idea if/when it will. @me-no-dev maybe?

**Comment by me-no-dev** [comment]
Hopefully soon :)

**Comment by marvinroger** [comment]
@kenpeter it's the best ETA you will get. :)
Once it's implemented in the underlying TCP library, it will be a matter of days before it's usable in this library.

**Comment by me-no-dev** [comment]
We are looking into ssl libs that can work asynchronously and that can be implemented in ESP8266 and ESP32 and have a few ideas, but nothing solid yet. Surely at some point in the near future the lib will support SSL, but I can not really say when exactly :)

**Comment by marvinroger** [comment]
Thanks for the information :)

**Comment by marvinroger** [comment]
SSL/TLS will be available for AsyncMqttClient when [esp8266/Arduino](https://github.com/esp8266/Arduino) 2.4.0 is released, thanks to @me-no-dev which implemented it in ESPAsyncTCP.

**Comment by drejkus** [comment]
Can someone please point me in the right direction how to use SSL? Third party means using ESPAsyncTCP? An example would be perfect..

**Comment by DavidM42** [comment]
Is there new information on how to use it with this library? I would also be interested to implement it into my project.

**Comment by Nzbuu** [comment]
Looks like we're still waiting for esp8266/Arduino 2.4.0 to be released

**Comment by s00500** [comment]
Puh this is a big drawback in the 2.x version... anyway this whole library is pretty awesome, it woud be great if the ssl support is working again

**Comment by marvinroger** [comment]
The AsyncMqttClient will support SSL, it just cannot be implemented for the moment until 2.4.0 is released as it would be break the current code otherwise.

**Comment by marvinroger** [comment]
SSL has been implemented by @allanbartley. It will be released with v0.8.0 and will require esp8266/Arduino 2.4.0.

**Comment by marvinroger** [comment]
Released!

**Comment by kenpeter** [comment]
finally finally finally......

**Comment by marvinroger** [comment]
I'd appreciate feedback, see if everything is working as it should 😊

**Comment by allanbartley** [comment]
I'll re-test in a fresh project and do a quick example tonight.

**Comment by allanbartley** [comment]
There are a couple of little bugs, which I'm working on a pull request for now.
There is also an issue where if the client is disconnected due to a bad fingerprint, there is a crash on attempting to reconnect. I haven't figured that one out yet. Should I raise an issue for this?
