### ISSUE TITLE
Static onAck

### ISSUE THREAD

**Issue by brunoudi** [marvinroger/async-mqtt-client#155]
In the library, the callback for AsyncClient.onAck is static

https://github.com/marvinroger/async-mqtt-client/blob/8bd918bfeb2f197afa8b0cb5d278ab2942c62ccb/src/AsyncMqttClient.hpp#L145

I'm doing some improvements to send large packets, where I'm waiting the onAck callback to send the chunk packets.

It's working well. I included some control variables but I had to remove the static modifier because I was getting this compiling error:

`invalid use of member 'AsyncMqttClient::myVariableName' in static member function`

It is not clear to me, because the others callback are not static.

So the point is: Can I remove the modifier static, or considering I'm not a professional developer is there a better way to acess my control variables from onAck callback?

**Comment by bertmelis** [comment]
You can remove "static".

In the current code, this function does nothing so it doesn't matter if it is static of not.

The same goes for _onError.
