### ISSUE TITLE
The onMessage callback adds some cyrillic endings to the topic and the payload message

### ISSUE THREAD

**Issue by x0tester0x** [marvinroger/async-mqtt-client#168]
`void onMqttMessage(char* topic, char* payload, AsyncMqttClientMessageProperties properties, size_t len, size_t index, size_t total)`
`{`
`Serial.println(topic);`
`Serial.println(payload);`
`}`

Example:
I'm sending "LOCATE" and I will get this "LOCATE⸮" or this "LOCATE⸮⸮\l⸮⸮⸮r @" or this "LOCATEXEZT⸮⸮x⸮!@⸮⸮⸮?L⸮⸮?" back.

I couldn't figure out what's the mistake.
Can someone help me, please?

**Comment by jeroenst** [comment]
The string is not 0 terminated, so use the parameter len to print the number of characters.

**Comment by x0tester0x** [comment]
Ok, I understand. It works fine now, but how can I then store the right value in a variable?

**Comment by jeroenst** [comment]
Depends on what you want...

In my code I do this:
String payloadstring = "";
  for (int i = 0; i < len; i++)
  {
    payloadstring += char(payload[i]);
  }

**Comment by x0tester0x** [comment]
Later I want to compare it to another String...

**Comment by jeroenst** [comment]
You can use my example to compare it to your string.

**Comment by x0tester0x** [comment]
Yes I see. Is there not an existing function from Arduino to do this?

**Comment by jeroenst** [comment]
You can use strncat... But it makes life more difficult because you must declare an array of characters big enough to hold the incoming payload and prevent an overrun, also you have to use strcmp.

**Comment by x0tester0x** [comment]
A ok, but is there no alternative to a loop?

**Comment by jeroenst** [comment]
Maybe you can use:

char *str = realloc(payload, (len+1) * sizeof(char));
str[len] = 0;

**Comment by x0tester0x** [comment]
Could I not just add the null terminator and convert it with String(payload)?

**Comment by jeroenst** [comment]
Nope, because the payload variable has no room left at the end to add the null terminator (that's why you have to do a realloc or copy it character by character to a string)....

**Comment by x0tester0x** [comment]
Ok it looks like there is no other way around the loop... 
Then I have to use the loop

Thanks a lot for your help :)

**Comment by jeroenst** [comment]
You're welcome ;-)
