### ISSUE TITLE
Is this Library compatible with ESP8266WebServer and ESP8266HTTPUpdateServer?

### ISSUE THREAD

**Issue by x0tester0x** [marvinroger/async-mqtt-client#169]
I can't connect to the Webserver on the ESP8266 for OTA updates...
[https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#web-browser](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#web-browser)

**Comment by jeroenst** [comment]
I use it together with the default webserver and arduino ota.

**Comment by aliusc** [comment]
It works for me with http update. Had problems when called update directly from loop, but when function is called by set flag it works fine. https://github.com/marvinroger/async-mqtt-client/issues/175#issuecomment-576386223
