### ISSUE TITLE
Including the library breaks mutli .ino build

### ISSUE THREAD

**Issue by matijagaspar** [marvinroger/async-mqtt-client#17]
As the title says, if I include the AsyncMqttClient.h library in any of the sketches, I can not call functions from other tabs(ino files).

Simple to reproduce:
Create new sketch and add a new tab whatever the name
main.ino
```
#include <AsyncMqttClient.h>
void setup() {
  test();
}
void loop() {}
```

test.ino

```
int test(){
  return 1
  }
```

It will compile if `#include <AsyncMqttClient.h>` is removed.

**Comment by marvinroger** [comment]
I cannot reproduce with Arduino 1.6.10, esp8266/Arduino 2.3.0 and latest git of AsyncMqttClient and ESPAsyncTCP: the code compiles fine. Could you please retry with everything up-to-date?

**Comment by marvinroger** [comment]
Closin this issue, no updates from the OP. Feel free to reopen.
