### ISSUE TITLE
Anyway of Knowing when the mqtt Ping is happening?? 

### ISSUE THREAD

**Issue by jassi00713** [marvinroger/async-mqtt-client#172]
Hi..

I am developing an mqtt based application on ESP8266.
One of the routines i am running is keeping a check on free heap in ESP8266.

I notice when there is a mqtt ping going out, there is a dip in free heap.

Is the a callback or function to know when this ping takes place.
I checked out the library and found certain variables like lastClientActivit, lastServerActivity, lastPingRequestTime but they are all private to the library.

Any way of knowing it directly in my application code when this ping takes place?

Thank you
Really hoping for a solution to this

**Comment by kleini** [comment]
I have no idea, what you mean by a MQTT ping? If you're talking about the statistics of every Homie device, that is send regularly, then there is an event where you can listen on. See on page https://homieiot.github.io/homie-esp8266/docs/develop-v3/advanced-usage/events/ the event `HomieEventType::SENDING_STATISTICS`.

**Comment by bertmelis** [comment]
No, it is not exposed. Underlying lib asynctcp calls _onPoll every 125ms (?) and this lib decides when to send the Ping based on activity and keepalive.

The only way to know is to change the code  and implement it yourself.

**Comment by jassi00713** [comment]
ok ... what minimal thing should i do to achieve that?
will making those variables public in the library do it?

**Comment by jeroenst** [comment]
You would have to create a callback like onPing and onPingAck, and call them in the library at the point where the ping is send and where the ping ack is received.

**Comment by jassi00713** [comment]
Thanx ... i will look into it

**Comment by luebbe** [comment]
Closing old issue
