### ISSUE TITLE
Esp32 mqtt over websocket?

### ISSUE THREAD

**Issue by soheils2** [marvinroger/async-mqtt-client#176]
Hi is there any way your code connect mqtt over "ws://" cause this is what I've looked everywhere and found nothing with any library or add-on!

Can you help me with this? 

******Ps:*****
I also ran to some s.hit from espressif  called mqtt-clinet.h. That i didn't succed to run it correctly (somehow event handlesr are not implimented !
Im tired of searching and founding literally nothing 😔

https://github.com/espressif/arduino-esp32/issues/3639

**Comment by soheils2** [comment]
nothing?

**Comment by bertmelis** [comment]
this lib doesn't support websocket connections.

**Comment by jigneshk5** [comment]
@bertmelis Do you know any arduino library that support websocket connections for Mqtt?

**Comment by bertmelis** [comment]
You can use the lib in IDF for esp32. It even has secure websockets. Example here: https://github.com/espressif/esp-idf/tree/master/examples/protocols/mqtt
