### ISSUE TITLE
Push new release to Arduino/PlatformIO?

### ISSUE THREAD

**Issue by nullstalgia** [marvinroger/async-mqtt-client#185]
It's been a couple years since the last Release, and maybe those commits since then would be a good thing to send out to the public?

**Comment by hachi** [comment]
Yes, please.

**Comment by bluelu** [comment]
Yes, this would be great!

**Comment by thijstriemstra** [comment]
+1. ping @marvinroger

**Comment by marvinroger** [comment]
`master` is 2 commits ahead of `develop`, and there are merge conflicts, so I'm not able create a new release right now.
@bertmelis thanks for all the work done here 😃 can you merge `master` into `develop`, so we can prepare the release (bump the version) on `develop` before we merge it to `master`?

**Comment by bertmelis** [comment]
I'll look into it. Holiday season is coming up though and I've got some catching up to do now everything is opening up again 😄 .

Documentation also has to be updated.

**Comment by bertmelis** [comment]
After checking my calendar, I can set myself a deadline by the end of July.

**Comment by bertmelis** [comment]
So I'm back.

Few lasts checkes:
- I thought about adding a "clearQueue" method, to be called when **disconnected**. This is not MQTT compliant, but might be handy in some cases.
- API is not changed but it is also more then a bugfix release, so v0.9.0 would fit?
- Anything missing?

We're not launching a new Apollo mission but I also want to make sure we're not missing anything obvious.

**Comment by proddy** [comment]
Agree, the develop branch is so much more than a patch release. so 0.9.0 seems appropriate. I've been using the dev branch in all my projects and some are being used by 2000+ users so it's stable enough. If you add functions you'll also need to update the docs and example code which is a bit more housekeeping.

**Comment by bertmelis** [comment]
There you have it, I forgot about updating the docs.

**Comment by bertmelis** [comment]
Release 0.9.0 will be picked up soon by the Pio library bot (I hope).
