### ISSUE TITLE
Connect with AWS IoT Core

### ISSUE THREAD

**Issue by am-canes** [marvinroger/async-mqtt-client#189]
Is it possible to use AsyncMqttClient library to connect with amazon AWS IoT Core?
Anyone has an example ou could help me?
I was using pubSubClient with WifiSecureClient but my code was being blocked and I have some critical process and the code never can be blocked.

Thank you.

**Comment by bertmelis** [comment]
As far as I know, it is not supported. Reason: TLS1.2 is not supported by AsyncTCP.

**Comment by am-canes** [comment]
Thanks @bertmelis. I will try to find another solution.
