### ISSUE TITLE
FullyFeatured-ESP8266 example sketch won't compile in PlatformIO

### ISSUE THREAD

**Issue by AlbanT** [marvinroger/async-mqtt-client#192]
I'm trying to redo some of my Arduino sketches in PlatformIO and because I ran into some problems with MQTT I decided to first start again with the example sketch.

When I try to compile the **FullyFeatured-ESP8266** sketch for my Wemos D1 mini pro I get the following errors
`error: no matching function for call to 'Ticker::Ticker()'`
`error: 'class Ticker' has no member named 'detach'`
`error: 'class Ticker' has no member named 'once'`

Could it be that this library uses an old version of the Ticker library? I have tried V1.0.1, V2.0.2, V2.1.0 and V3.1.5 (in reverse order of course..) The older V2 and V1 did get rid or the first error but the ones about **detach** and **once** remained.

Any ideas on how I can fix this? Or a simple example without the Ticker library.

For the record I had to move some of the methods up in order to satisfy the forward declaration in PlatformIO. It seems that the Arduino IDE is less strict.

**Comment by bertmelis** [comment]
There's something wrong with your installation. Ticker is included in the Arduino core so you should not have it as separate library.

Arduino IDE indeed tolerates functions not being declared before use (which off course is not standard C++ practice).
