### ISSUE TITLE
send large payload

### ISSUE THREAD

**Issue by farsajik** [marvinroger/async-mqtt-client#195]
hi friends.thank you for this awaseme library.i want to send image from esp32 over mqtt.i converted image to base64 format.but i can only send half of data.how to send 13000 bytes?thanks

**Comment by bertmelis** [comment]
https://github.com/marvinroger/async-mqtt-client/pull/184

**Comment by bertmelis** [comment]
Meanwhile you can send payloads as large as heap memory allows. Improvements are in the develop-branch.
