### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kiralikbeyin** [marvinroger/async-mqtt-client#20]
Auto read a file and send response when got a "trigger message"  from broker?

**Comment by marvinroger** [comment]
I don't understand what you mean, could you please clarify?

**Comment by kiralikbeyin** [comment]
Broker to client -> "read a.json file and send me file content"
Esp-> open a.json file , read string, response to broker with file content.

Like mqttClient.publish("file/a.json", 0, true, "{"a":"json content"}" );

**Comment by marvinroger** [comment]
AsyncMqttClient is intentionally low-level: it only provides raw MQTT stuff. What you're asking for can be achieved at the sketch level. This feature might be part of a higher level library, though, but I won't be the one creating this library, sorry.
