### ISSUE TITLE
Error "assert failed!" when using Arduino Ethernet library

### ISSUE THREAD

**Issue by mrdc** [marvinroger/async-mqtt-client#200]
Hi,

I'm trying to use AsyncMQTT with Ethernet instead of WiFi on ESP32. And I get this error:
```
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088071 on core 1
```
on `mqttClient.connect(); `

I'm using Arduino Ethernet library (2.0.0) with this example (without timers): https://github.com/marvinroger/async-mqtt-client/blob/master/examples/FullyFeatured-ESP32/FullyFeatured-ESP32.ino 
Have tested with `Pubsubclient `and my "ethernet" code works. The difference I see is that in `Pubsubclient `we explicitly specify the "transport" layer:
```
EthernetClient ethClient;
PubSubClient client(ethClient);
```
Any ideas?

**Comment by bertmelis** [comment]
This lib doesn't support the Ethernet lib. It is built on top of AsyncTCP.
