### ISSUE TITLE
ESP8266 keeps connecting and disconnecting with reason **TCP_DISCONNECTED**

### ISSUE THREAD

**Issue by Abhimanyu6676** [marvinroger/async-mqtt-client#209]
AsyncMqttClient starts randomly connecting and disconnecting from the broker.
```
[MQTT] connection: Success connected
[MQTT] subscribing: Subscribed
[MQTT] connection: Disconnected = TCP_DISCONNECTED (0)
[MQTT] connection: Success connected
[MQTT] subscribing: Subscribed
[MQTT] connection: Disconnected = TCP_DISCONNECTED (0)
[MQTT] connection: Success connected
[MQTT] connection: Success connected
[MQTT] subscribing: Subscribed
[MQTT] connection: Disconnected = TCP_DISCONNECTED (0)
[MQTT] connection: Success connected
[MQTT] connection: Success connected
[MQTT] connection: Success connected
[MQTT] connection: Disconnected = TCP_DISCONNECTED (0)
[MQTT] connection: Success connected
[MQTT] subscribing: Subscribed
```

**Comment by re3lex** [comment]
yeah, same issue here. 
There is no issue with WiFI connection (I can reach running http server on ESP8266), as mqtt broker is accessible.

**Comment by bertmelis** [comment]
Does the broker's log say "socket error"? (in case of mosquito)

**Comment by re3lex** [comment]
Yes. 

I suspect something wrong with TCPAsync library but  not with mqtt client.

**Comment by bertmelis** [comment]
You can add a third parameter to every `_client.add()` statement in this lib (this lib, not the asynctcp) link this for example:
https://github.com/marvinroger/async-mqtt-client/blob/7f1ba481a22d56ccf123e4b2f6e555d134c956d0/src/AsyncMqttClient.cpp#L313


`_client.add(fixedHeader, 1 + remainingLengthLength);`
becomes
`_client.add(fixedHeader, 1 + remainingLengthLength, 0x01);`

Adding this parameter makes the TCP library copy the data instead of taking a reference to the data and hance avoids invalid pointer problems like you're suffering from.

PS This flag is added by default on ESP32 but not on ESP8266. So ESP32 does not suffer from this issue.

**Comment by re3lex** [comment]
@bertmelis 
> So ESP32 does not suffer from this issue.
well, looks like I see the same issue on my ESP32 setup too. I didn't dig it in detail though, but as per behavior mqttClient is disconnecting time to time. Added `ESP.restart()` for  now as quick workaround.

Anyway thanks for tip. I will apply it and report back about results.

BTW: found that if I call `mqttClient.setWill()` before calling `mqttClient.connect()` then mqttClient cannot connect to server in 100% cases.

**Comment by re3lex** [comment]
> Anyway thanks for tip. I will apply it and report back about results.

yeah, that fixed the issue looks like!
I will test it further but mqtt server restart doesn't cause infinite disconnect-connect loop after this fix.

Thanks, @bertmelis !

**Comment by bertmelis** [comment]
The will issue is something that might need better documentation.

The will topic and payload is not saved within the library. It is also not "used" when yo user it, or even on calling connect.

So you have to make sure the pointer you passed on to the lib is still valid throughout the life of the MQTT client object. Easiest is to make it a global or static variable.

**Comment by re3lex** [comment]
Yeah, already found out that at least Will topic name must be declared as global variable if it is generated dynamically.

thanks for your help!

**Comment by Gornerrrrr** [comment]
> @bertmelis
> 
> > So ESP32 does not suffer from this issue.
> 
> well, looks like I see the same issue on my ESP32 setup too. I didn't dig it in detail though, but as per behavior mqttClient is disconnecting time to time. Added `ESP.restart()` for now as quick workaround.
> 
> Anyway thanks for tip. I will apply it and report back about results.
> 
> BTW: found that if I call `mqttClient.setWill()` before calling `mqttClient.connect()` then mqttClient cannot connect to server in 100% cases.
> [re3lex](/re3lex)

Same problem in 2024. 
Calling 'mqttClient.setWill()' and `mqttClient.connect()` then mqttClient cannot connect to server. 
Error message "asyncTCP: pcb is NULL".
