### ISSUE TITLE
Make a configurable limit on topic length

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/async-mqtt-client#22]
The only way to crash the device currently is by sending a message on a topic with a length larger than what the ESP8266 RAM can handle. A `setMaxTopicLength()` function could be added, so the topic buffer would be allocated once, and the message would be skipped if the topic length is larger than the limit. What would be a good default? Can you guys tell me what's the longest topic you use?

**Comment by eos1d3** [comment]
Hi,

I don't know why people will need very large length for this. I believe 32 to 128 bytes is more than enough. What do you think?

**Comment by marvinroger** [comment]
For homie for example, topics can be like `base-topic-devices/firstfloor-bedroom-device/temperature/degrees/set`, which is 68 bytes already. So yes, I guess 128 bytes is a safe default.

**Comment by marvinroger** [comment]
Implemented in 3f8cc2fe63dd9911e57a83ca0f2a8ffc8805bc16
