### ISSUE TITLE
Do not subscribe over 4 topics

### ISSUE THREAD

**Issue by micdj** [marvinroger/async-mqtt-client#228]
ESP8266mod 160 mhz HIGH Bandwidth no feat.

I try to subscribe over then 4 topics, but it doesn't work, it connects to mqtt broker, but not receive payload for topics subcribed from the fifth.
Sometimes it disconnect from mqtt broker.

**Comment by bertmelis** [comment]
Could you try the develop branch instead of master?

**Comment by bertmelis** [comment]
I believe this is fixed now. There was an issue with packet IDs.

**Comment by IoTopsDeveloper** [comment]
I am encountering the same issue in this, the payload is not subscribed after 5 messages

**Comment by bertmelis** [comment]
could you try with the `develop` branch instead of `master`?
