### ISSUE TITLE
(develop) publish stuck with QOS 1

### ISSUE THREAD

**Issue by proddy** [marvinroger/async-mqtt-client#236]
Hi @bertmelis, I ran into an issue with the latest `develop` branch using QOS1. I don't have an example sketch to reproduce this nicely but basically, this is the sequence that fails in my project:
 - ESP32
 - set QOS to 1, plain authentication, nothing spectacular
 - Publish something from the ESP. A Packet ID is returned and the `on_publish` callback function is called (all OK)
 - Send an MQTT message to the ESP and it's correctly received and handled by the `on_message` callback (all OK)
 - now Publish something again. A Packet ID is returned, but the message is not transmitted to lwip. Also the `on_publish` is not called (not OK!)

Any idea what could be causing this?

CC @MichaelDvP who discovered this on https://github.com/proddy/EMS-ESP/issues/717#issuecomment-788818934

**Comment by bertmelis** [comment]
Got it. I leave the closing of the issue up to you. I didn't test this.

https://github.com/marvinroger/async-mqtt-client/pull/237
