### ISSUE TITLE
Is there a danger of using `String("xox").c_str()`

### ISSUE THREAD

**Issue by sticilface** [marvinroger/async-mqtt-client#25]
I'd like to know if there is any problem of using temporary strings within a function to send a mqtt message.  Does you lib copy them over to a buffer for sending later, or resending if the ack is not received?

**Comment by marvinroger** [comment]
There's no danger, the data is copied into the lwip buffer, and everything is handled there.

**Comment by sticilface** [comment]
Cool thanks.
