### ISSUE TITLE
Received subscribe with undefined character

### ISSUE THREAD

**Issue by dongtranthien** [marvinroger/async-mqtt-client#255]
Publish send: 1.0.4
But received:
1.0.4�5␇�? �?     �ﾭ�xV��
1.0.4?␔
1.0.4?xV��xV��    �ﾭ�xV��

Thanks for help :D

**Comment by bertmelis** [comment]
https://github.com/marvinroger/async-mqtt-client/blob/develop/docs/5.-Troubleshooting.md
