### ISSUE TITLE
Problem with Fingerprint verification

### ISSUE THREAD

**Issue by miloit** [marvinroger/async-mqtt-client#259]
Hello,

I tried the ssl sample code from you and generated a fingerprint

I use this as test server: https://test.mosquitto.org/

I generated the Fingerprint via openssl x509 -fingerprint -in mosquitto.org.crt -noout -inform pem -sha1
But the result is Bad Fingerprint.

What I am doing wrong?

**Comment by bertmelis** [comment]
You're sure you're using the right port?
Is your fingerprint the same as when generates by the script provided in this repo?

**Comment by miloit** [comment]
Closed
