### ISSUE TITLE
async-mqtt-client cannot compile with Arduino 1.16.11 and esp8266 2.3.0

### ISSUE THREAD

**Issue by kenpeter** [marvinroger/async-mqtt-client#26]
The error is:

> error: expected unqualified-id before '(' token
> # define max(a,b) ((a)>(b)?(a):(b))

I cannot remember the fix. It seems I need to redefine max in async-mqtt-client. Any advice?

![error](https://cloud.githubusercontent.com/assets/927150/19297316/81d93b8e-908f-11e6-9571-164ab4d4740f.png)

![arduino h](https://cloud.githubusercontent.com/assets/927150/19297318/85ed3d38-908f-11e6-8583-c28d634e46b8.png)

**Comment by marvinroger** [comment]
What's your sketch? See https://github.com/esp8266/Arduino/issues/398

**Comment by karlp** [comment]
I had this, but fixed it by moving the include of ```<AsyncMqttClient.h>``` to "last"  (at least after some of the esp8266 headers)

I suspect asyncmqttclient.h should get some extra includes in it, so it doesn't depend on other libraries pulling in the right things.

**Comment by marvinroger** [comment]
No, this is an esp8266/Arduino issue, see the issue linked above. I cannot do anything from async-mqtt-client, unfortunately.

**Comment by marvinroger** [comment]
Closing it as we can't do anything on our side.
