### ISSUE TITLE
setServer to use hostname instead of IP address

### ISSUE THREAD

**Issue by hakam80** [marvinroger/async-mqtt-client#27]
AsyncMqttClient& setServer(IPAddress ip, uint16_t port)

Is it possible to use hostname instead of IP address?

**Comment by marvinroger** [comment]
Of course, look at the API: https://github.com/marvinroger/async-mqtt-client/blob/master/docs/2.-API-reference.md

**Comment by hakam80** [comment]
Sorry, I was blink from seeing the next command

**Comment by hakam80** [comment]
Hi,
With IP address I can connect to mqtt broker, but with host name it is not connecting to mqtt broker, any advise?

#define MQTT_server IPAddress(100, 100, 1,110) //Ok, connection to broker established
#define MQTT_server "Bo19-srv" //Not working

**Comment by hakam80** [comment]
Hi,
Any comment about why using hostname in MQTT_server is not working?

**Comment by marvinroger** [comment]
Sorry for the late response.
A valid domain is an FQDN, `Bo19-srv` is not. AsyncMqttClient does not support mDNS and co, sorry!
