### ISSUE TITLE
error ticker.h

### ISSUE THREAD

**Issue by TitQuentin** [marvinroger/async-mqtt-client#274]
Hi all ! 

I have this erros when I verify the code :

McLighting:5:10: fatal error: Ticker.h: No such file or directory
 #include <Ticker.h>
 
 What is the missing library .

Can you help me please?
Thx !

**Comment by bertmelis** [comment]
Ticker is a library that is distributed with the Arduino core for both esp8266 and esp32.

Id say it's a problem with your installation of the core.

**Comment by kleini** [comment]
If you turn off the Library Dependency Finder in PlatformIO you have to add Ticker to the library dependencies like here
https://github.com/kleini/sonoff-4ch/blob/master/platformio.ini#L33

**Comment by TitQuentin** [comment]
Thx ! It"s Work :)
