### ISSUE TITLE
OnDisconnect Never Called when Internet is Off.

### ISSUE THREAD

**Issue by rndalteem** [marvinroger/async-mqtt-client#281]
I have implemented my code using Lib and while testing i found when internet is turned off library never call OnDisconnect Callback. I have attached log when Internet is off.
I am using Latest Release 0.9.0

![Annotation 2022-03-07 154457](https://user-images.githubusercontent.com/84010961/157011227-2483e413-5d03-47aa-8f6b-a85c8e0268d3.png)

**Comment by bertmelis** [comment]
To have things clear: keepalive is kept default and the connection to the broker is interrupted.

Yes?

**Comment by proddy** [comment]
And clean session is disabled?

**Comment by ktannady** [comment]
Hello, thanks for your reply.

> To have things clear: keepalive is kept default and the connection to the broker is interrupted.

> And clean session is disabled?

Yes, the connection to the broker is interrupted, I have never called the keepalive and clean session function so I think it is the default 15 seconds for keepalive and true for the clean session.

for some quick fix, I added the `ESP8266Ping` function to check if there is a connection to the broker, if not I just call the `mqttClient.disconnect()` function to trigger the `onDisconnect()`.

**Comment by bertmelis** [comment]
I have to add some extra debug statements at the keepalive handling. It should disconnect at twice the keepalive.

**Comment by ktannady** [comment]
> 

Hello, thanks for your reply.
I don't know how and where to compile the library with debug statement, can you help me?

**Comment by bertmelis** [comment]
I'm on holiday now and only limited access to my computer. Are you using Arduino IDE or Platformio or a different IDE?

**Comment by ktannady** [comment]
> I'm on holiday now and only limited access to my computer. Are you using Arduino IDE or Platformio or a different IDE?

I'm using Platformio.

**Comment by iggy80** [comment]
The problem is located in the _handleQueue method (fileAsyncMqttClient.cpp line 394).
The _lastPingRequestTime variable is reset to 0 at line 410, then the _onPoll keeps sending PingRequests.
Just remove or comment the _lastPingRequestTime = 0; and the disconnect now fires after keep alive delay when broker is disconnected.....

**Comment by bertmelis** [comment]
@iggy80 PRs welcome!

**Comment by rndalteem** [comment]
@iggy80 I have tested its working now.Thanks.

**Comment by ktannady** [comment]
Hello, there is no PR yet?

**Comment by bertmelis** [comment]
> Hello, there is no PR yet?

#284
