### ISSUE TITLE
DoS attack on MQTT

### ISSUE THREAD

**Issue by baesuzyzue** [marvinroger/async-mqtt-client#288]
1) How to do a Denial of service (DoS) attack on MQTT on client and server? (Ubuntu)

2) How can I use a tool such as "mosquitto_pub" to publish a large number of messages to the "/test" topic, which will cause the MQTT broker to become overloaded and unavailable for other clients? (Ubuntu)

3) How to use the 'mosquitto_sub' command to subscribe to a large number of topics, and causing the broker to become overwhelmed? (Ubuntu)

**Comment by Pablo2048** [comment]
Really? RTFM & STFW if you are really interested. This "issue" has nothing to do with this library.
