### ISSUE TITLE
MQTT broker autentication

### ISSUE THREAD

**Issue by 100000watt** [marvinroger/async-mqtt-client#300]
Hi, How do I enter my username and password to authenticate to the broker Mosquitto? 
AsyncMqttClient.setCredentials always returns error.
Forgive me, I'm a novice. 
Thank you

**Comment by mtsSwitzerland** [comment]
For me this works


void connectToMqtt()
{
    if (setupInfo == true)
    {
        Serial.println("Connecting to MQTT...");
    }
    if (mqttUser && mqttPassword)
    {
        mqttClient.setCredentials(mqttUser, mqttPassword);
    }
    mqttClient.connect();
}
