### ISSUE TITLE
Call ESP8266httpUpdate within on_mqtt_publish. Return connection refused

### ISSUE THREAD

**Issue by kenpeter** [marvinroger/async-mqtt-client#4]
Call ESP8266httpUpdate within on_mqtt_publish. ESP8266httpUpdate returns connection refused. i.e. not able to download firmware. If I call ESP8266httpUpdate within void setup(). It is able to download the firmware.

![connection_refuse](https://cloud.githubusercontent.com/assets/927150/15503594/fe067c72-21fd-11e6-85da-cc0ae1084664.png)

Full code is here.
https://github.com/kenpeter/mqtt_esp_http_update_sample/blob/master/phone.txt
https://github.com/kenpeter/mqtt_esp_http_update_sample/blob/master/device.txt

The idea is that the phone.txt fire a json command, then it triggers on_mqtt_publish in device.txt, then it calls ota_update()

**Comment by marvinroger** [comment]
ESP8266httpUpdate won't work in the callback anyway, because ESP8266httpUpdate is a synchronous library. Try to set a flag (instead of your `ota_update()`), and check from within your main `loop()` if this flag is set, and if so call your `ota_update()`.

**Comment by kenpeter** [comment]
Thank you. This makes sense.
