### ISSUE TITLE
unable to access the "char* topic" and "char* payload" inside "void loop()" after saving values in global variables.

### ISSUE THREAD

**Issue by abhaysbharadwaj** [marvinroger/async-mqtt-client#56]
Hi,
First of all, thank you for this amazing library!

I am facing one issue. And I am not able to resolve it.

in the following function:

```C
void onMqttMessage(char* topic, char* payload, AsyncMqttClientMessageProperties properties, size_t len, size_t index, size_t total)
{
    payload_new = payload;
    topic_new = topic;
    Serial.println("** new message received **");
    Serial.print("topic: ");
    Serial.println(topic_new);
    Serial.print("payload: ");
    Serial.println(payload_new);
}
```
here, ```payload_new``` and ```topic_new``` are ```char*``` declared as global (before setup() ).

I am able to get the values inside the above function. But when I try to print them inside loop(), it gives a blank space.
```C
void loop()
{
    Serial.println("reveived value is: ");
    Serial.println(payload_new);
}
```
How can I access the values of those variables inside the loop() as well?

I apologise if this is a noob question. But I tried googling and was not successful.

**Comment by marvinroger** [comment]
The buffer you get access to from the `onMqttMessage` is actually the raw TCP buffer, and is detroyed right after the callback exits. Therefore, all your logic should be handled from the callback.

However, if for some reason you need to access to the buffer from outside the callback, you need to copy it first to a variable you manage, see [memcpy](http://www.cplusplus.com/reference/cstring/memcpy).
