### ISSUE TITLE
using Async connection for a Server - Clinets connection

### ISSUE THREAD

**Issue by mkeyno** [marvinroger/async-mqtt-client#6]
hi  @marvinroger  sorry to make the issue for my question , actually I've planned to set a ESP module as AP and other ESP module as Station mode and like IOT home , the server received and send command to those , Iggre told me I should use asyinc lib instead of Esp8266WebServer lib , I really appreciated if you could guide me to what strategy should follow

**Comment by marvinroger** [comment]
MQTT needs a broker to work, this project is a client. What you're asking is doable if someone implements a MQTT broker on the ESP8266, though.

**Comment by mkeyno** [comment]
thanks for quick reply , Actually I intend to make sketch for both AP and Station mode , in AP mode , modules converted  to asysnc webserver which can gather data form all other station and probably send the command or acknowledgment to them , I think in simple home IOT, number of device or sensor wont exceed than 10 modules and async webserver can handle that, but I'm don't know how to install MQTT service for both mode , also in setup configuration I should make rule that each station introduce itself to AP module and register its IP and all sensor info that attached to it
during this post I reviewed the ESPeasy repo, they make very pretty IOT solution but yet can't figure out how to add other ESP module to AP module

**Comment by marvinroger** [comment]
Your AP needs to be configured as a MQTT *broker*, this project is a *client* which needs a broker to communicate with (which is out the scope of this project).

**Comment by mkeyno** [comment]
probably do you know such project or lib that go such way (MQTT broker)

**Comment by marvinroger** [comment]
Sorry, I don't!

**Comment by eos1d3** [comment]
You can use Mosquitto - An Open Source MQTT v3.1/v3.1.1 Broker
http://mosquitto.org/

It runs on many different platforms and include Raspberry PI.

i just tested it on Raspberry PI 3 and it works very well with this async client library.

**Comment by marvinroger** [comment]
I thought you were asking for a MQTT broker on the ESP8266, but yes, mosquitto is the *leading* (I'm not sure if it is an "official" MQTT project).

Glad you achieved what you want.
