### ISSUE TITLE
Compiler error on PlatformIO

### ISSUE THREAD

**Issue by tanker11** [marvinroger/async-mqtt-client#63]
I have installed the library on Platformio and tried the examples.
First example (main.cpp) compiles fine, but the FullyFeatured.ino does not, saying connectToMqtt is not declared in scope.
Libraries are installed as described in the instructions.

Additional comment: on Arduino IDE it compiles just fine. The reason I am trying to use Plaformio is that ESP8266MQTTMesh library cannot be installed into it (it uses AsyncMqtt).

**Comment by bertmelis** [comment]
I assume this is already solved.
