### ISSUE TITLE
Delete mqttClient ?

### ISSUE THREAD

**Issue by kiralikbeyin** [marvinroger/async-mqtt-client#87]
Is it possible to remove mqttClient like
```
  mqttClient.destroy();
````

**Comment by timpur** [comment]
Nope, but should be a thing.

**Comment by kiralikbeyin** [comment]
@marvinroger

**Comment by bertmelis** [comment]
Destroying the client is supported (at least in the `development` branch). However **not when using TLS** --> crash.
