### ISSUE TITLE
sprintf with current Arduino IDE for ESP32

### ISSUE THREAD

**Issue by ghost** [marvinroger/async-mqtt-client#91]
`sprintf(_generatedClientId, "esp32%06x", ESP.getEfuseMac());`
needs to be changed to:
`sprintf(_generatedClientId, "esp32%" PRIu64, ESP.getEfuseMac());`

Because uint64_t is aka long unsigned int (makes sense, but dont ask me why it wasnt in the past) and not unsigned int. That causes a compilation error.

**Comment by bertmelis** [comment]
they changed it in the Arduino core for esp8266. But there are already a few pull requests.

**Comment by luebbe** [comment]
closing stale issue
