### ISSUE TITLE
esp32 crashes onMqttDisconnect() -> Guru Meditation Error

### ISSUE THREAD

**Issue by engrziarehman** [marvinroger/async-mqtt-client#99]
i am using esp32 with ethernet module lan8720, every thing working fine except when onMqttDisconnect() event rises following error appears and esp32 crashes.

Disconnected from MQTT.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited)
. Exception was unhandled.
Register dump:
PC      : 0x401096b3  PS      : 0x00060330  A0      : 0x800d62e8  A1      : 0x3ffdca90  
A2      : 0x00000000  A3      : 0x00000001  A4      : 0x0000000a  A5      : 0x00022203  
A6      : 0x00000000  A7      : 0x00004034  A8      : 0x80112d50  A9      : 0x3ffdca60  
A10     : 0x3ffdbe18  A11     : 0x3ffc10d0  A12     : 0x3ffdbe78  A13     : 0x00000000  
A14     : 0x3ffdbed8  A15     : 0x00000000  SAR     : 0x00000008  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x401096b3:0x3ffdca90 0x400d62e5:0x3ffdcab0 0x4010290d:0x3ffdcad0

Rebooting...

**Comment by vsimonaitis** [comment]
I have the same problem. 
It happens when running when executing vanilla basecamp sketch
`iot.mqtt.disconnect();`
in https://www.arduinolibraries.info/libraries/basecamp on ESP32 dev kit

**Comment by timpur** [comment]
Can you test one of our examples and send me the sketch, need to make sure it's not coming from Basecamp

**Comment by vsimonaitis** [comment]
I added disconnect state into onMqttMessage event I get the same exception

[ESP32mqtt_test.zip](https://github.com/marvinroger/async-mqtt-client/files/1981055/ESP32mqtt_test.zip)

**Comment by sysizlayan** [comment]
I am trying the fully featured example for ESP32.
In the test, I am connecting my ESP32 to mobile hotspot, waiting for the mqtt connection, then reading the sent and received packets.

After this, I am disabling the hotspot. As expected, ESP32 tries to reconnect to the network. While waiting, probably MQTT timeout occurs and onMqttDisconnect is called. 
I have added 2 serial messages to beginning and end of the function. both of them is printed.

Then I got the Core1 panicked error with loadprohibited message. Accorging to the "arduino-esp32" guys, it is probably because of trying to reach a NULL pointer.

Is something freed in "onDisconnect" event?

**Comment by gnampf89** [comment]
try this patch: `_sendDisconnect()` already calls `_client.close()`, that is why `_client.send()` probably crashes.
```
diff --git a/src/AsyncMqttClient.cpp b/src/AsyncMqttClient.cpp
index b3eff71..7a85814 100644
--- a/src/AsyncMqttClient.cpp
+++ b/src/AsyncMqttClient.cpp
@@ -704,7 +704,7 @@ void AsyncMqttClient::disconnect(bool force) {
   } else {
     _disconnectFlagged = true;
     _sendDisconnect();
-    _client.send();
+//    _client.send();
   }
 }
```

**Comment by timpur** [comment]
Will try, later today. If this is the case then this should be fixed in the lower lib not here... but good find :)

**Comment by smacyas** [comment]
I have the same problem...

.MQTT service channels published
.S G RA 01 0000: S->G: Read-Ack, Control setpoint = 0
G S RD 05 0000: G->S: Read-Data
.S G RA 05 0000: S->G: Read-Ack, Fault code = 0 0
MQTT Client getting disconnect
Disconnected from MQTT: 192.168.200.163:1883
.Guru Meditation Error: Core  1 panic'ed (LoadProhibited)
.. Exception was unhandled.
.Core 1 register dump:
.PC      : 0x4011f9bb  PS      : 0x00060d30  A0      : 0x800e8c50  A1      : 0x3ffe29b0  
.A2      : 0x00000000  A3      : 0x00000001  A4      : 0x00000023  A5      : 0x00006829  
.A6      : 0x00000000  A7      : 0x000032c4  A8      : 0x801287c0  A9      : 0x3ffe2980  
.A10     : 0x3ffdade0  A11     : 0x3ffc1100  A12     : 0x3ffdae40  A13     : 0x00000000  
.A14     : 0x3ffdaeb8  A15     : 0x3fff110c  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
.EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
.
.Backtrace: 0x4011f9bb:0x3ffe29b0 0x400e8c4d:0x3ffe29d0 0x40118ccd:0x3ffe29f0
.

**Comment by trycoon** [comment]
Is this issue fixed? Look like you found a bug, could the fix be merged soon?

**Comment by christianwicke** [comment]
I also had this problem. The suggested removal of the `_client.send();` fixed the crash for me. I created a pull request with this fix (https://github.com/marvinroger/async-mqtt-client/pull/118)

**Comment by EvertDekker** [comment]
Same problem here;
Guru Meditation Error: Core  1 panic'ed (LoadProhibited)
. Exception was unhandled. blah. blah...
When disconnecting from the broker.

I will try the patch to see if it works, can take up a week before the crash occurs. Let you know if it works.

**Comment by bertmelis** [comment]
Disconnecting is reworked completely in `develop` which should solve this issue. Closing.
